spring:
  data:
    rest:
      base-path: /api
  datasource:
    username: carlos
    password: 246810
#   url: jdbc:postgresql://my-testing-postgres.clha71iqoe17.us-east-1.rds.amazonaws.com/fra_db
    url: jdbc:postgresql://172.18.0.2:5432/fra_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 5000